### ISSUE TITLE
../OneWire/OneWire.h: No such file or directory

### ISSUE THREAD

**Issue by loptienm** [tomdeboer/SparkCoreDallasTemperature#2]
Veryfing code using this library in Particle Build fails with this error:

```
spark-dallas-temperature/spark-dallas-temperature.h:27:36: fatal error: ../OneWire/OneWire.h: No such file or directory
     #include "../OneWire/OneWire.h"
                                    ^
```

It looks like maybe it should just be "OneWire/OneWire.h".

**Comment by jenesaisdiq** [comment]
@loptienm Yeah, requires that you also add the OneWire library to your project, separately from this library. I've also just found that it doesn't work with the Photon, so I'm working on that now.

**Comment by loptienm** [comment]
Cool, I've gotten things working now finally, there weren't really any good
examples and I didn't understand the setup.  I have found that the Photon
does not work either and there seems to be a lot of issues with the
libraries.  Thanks for working on this!  Let me know if I can help, I work
as a firmware engineer at Seagate and can contribute some if you need any
help.

Good luck!

Thanks,

Mike

**Comment by tomdeboer** [comment]
@loptienm Thanks for mentioning. What is it you didn't understand about the examples?

@jenesaisdiq I have Spark Core running this library for a year or so, but I don't own an Photon yet, so I won't be able to test that yet I'm afraid.

But as soon as you get it working on the Photon, please let me know (or send a merge request) and I'd be happy to fix/merge it :)

Cheers,
Tom

**Comment by loptienm** [comment]
I guess my issue was finding a good example that used the OneWire library
and the Dallas Temperature library.  I eventually found one (but I don't
remember whose code it was).

Thanks,

Mike

**Comment by matteocontrini** [comment]
Any news on Photon support?

**Comment by jenesaisdiq** [comment]
Yeah @matteocontrini you should test it using the OneWire library I have in the gist at the bottom. 

@tomdeboer, could you also test it to make sure it gives you good data? If so, it'd be great if you could include the files with this library. I know it'd be better if you could easily include dependencies at the time of use, but that's not feature of our current library system and the need to add OneWire by hand is causing a lot of folks to get stuck. 

The other request I have, while you're reimporting your library to Particle Build, is to check that your examples are actually getting pulled in. The version that's showing in Build right now doesn't appear to have any, and I think that may just be a directory structure or older version thing. Look at spark/InternetButton, and let me know if you have any troubles with it.

Here's the OneWire that should work with both Cores and Photons:
https://gist.github.com/jenesaisdiq/5a1a151d16e4eeaf0e69
