### ISSUE TITLE
Negative temperature values return DEVICE_DISCONNECTED

### ISSUE THREAD

**Issue by CarmineM74** [tomdeboer/SparkCoreDallasTemperature#3]
Hi,

I'm using this library to monitor temperatures in the range -21..0 and I've discovered that, while
above 0 the library works perfectly, when temperature falls in that range it keeps
returning "DEVICE_DISCONNECTED".

After reading the DS18B20 data sheet, I've found that in the header file for the library the value DEVICE_DISCONNECTED_RAW should have been set at least to -7040.
At -7040 corresponds a temperature of -55 degrees Celsius.

Thanks for your work!

**Comment by tomdeboer** [comment]
I've just merged PR #4. That should fixed the problem you described.
